### ISSUE TITLE
Seing different things being shown on console log

### ISSUE THREAD

**Issue by DaveenDev** [webkong/vue3-toast#1]
Hello thanks for creating new version for toast.

No big real issue here but the console log outputs from toast when debugging our own apps, gets in the way. 

So i think it's good to remove them on the production.
![Capture](https://user-images.githubusercontent.com/57737577/182721074-f92a3a18-0c47-4fa9-8059-fcec658f29af.JPG)

**Comment by cpgb85** [comment]
I've been wondering myself as why this stuff is there lol.

**Comment by demiro** [comment]
sadly this plugin is not ready...
how can you release comments into production?

also, when you set different positions, if you don't pair it up with transition direction, will not work...

**Comment by webkong** [comment]
> Hello thanks for creating new version for toast.
> 
> No big real issue here but the console log outputs from toast when debugging our own apps, gets in the way.
> 
> So i think it's good to remove them on the production. ![Capture](https://user-images.githubusercontent.com/57737577/182721074-f92a3a18-0c47-4fa9-8059-fcec658f29af.JPG)

fixed.
